### ISSUE TITLE
編譯錯誤

### ISSUE THREAD

**Issue by WuJiLong** [yuhao-kuo/NKUST-thesis-template#39]
編譯時出現以下錯誤
./Configurations/template.tex:176: Package caption Error: 、’caption' undefined in families ’caption'.

註解以下報錯程式碼可正常編譯
./Configurations/template.tex 176: \captionsetup[centerlast,small,n]{caption} % setting caption
不知道註解後會造成神麼影響

**Comment by yuhao-kuo** [comment]
經測試此行可被省略，本文內容並不會受到影響。
