### ISSUE TITLE
groupadd: GID '20' already exists

### ISSUE THREAD

**Issue by LuHouRui** [yuhao-kuo/NKUST-thesis-template#55]
系統環境:macOS Big Sur 11.6

因為Mac預設使用者群組之ID為20，故導致Dockerfile無法新增使用者群組。

**Comment by yuhao-kuo** [comment]
USER / USERID 發生衝突表示使用者是 root 或是其他系統使用者，理論這種狀況不會發生，故不處理此問題。
如發生 user 衝突，請直接修改 docker/linux/build 的參數來指定使用者資訊。但請注意！當 USER / USERID 與本地端不符時，在非 docker 環境下操作 latex 檔案可能會有權限不足的問題發生。

**Comment by yuhao-kuo** [comment]
PR #56 修正此 Issues，closed！
